name: Java check with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'oracle'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Get short SHA
      run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
    - name: Generate release note
      run: |
        echo "JTool Release ${{ env.SHORT_SHA }}" >> RELEASE_NOTE
        echo "" >> RELEASE_NOTE
        echo "Updated JTool" >> RELEASE_NOTE 
    - name: Release file
      run: cat ./target/dict-1.0.jar
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        body_path: RELEASE_NOTE
        files: dict-1.0.jar
        name: JTool release ${{ env.SHORT_SHA }} 
        tag_name: v$(date +'%Y').$(date +'%m').$(date +'%d')