name: Java release with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  release:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'oracle'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Get short SHA
      run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
    - name: Generate release note
      run: |
        echo "JTool Release ${{ env.SHORT_SHA }}" >> RELEASE_NOTE
        echo "" >> RELEASE_NOTE
        echo "JTool已于$(date +'%Y').$(date +'%m').$(date +'%d')更新。" >> RELEASE_NOTE 
    - name: Get date
    - id: tag_name
        run: echo "VERSION=${date +v%Y.%m.%d}" >> $GITHUB_OUTPUT
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        body_path: RELEASE_NOTE
        files: target/dict-1.0.jar
        name: JTool release ${{ env.SHORT_SHA }} 
        tag_name: ${{ steps.tag_name.outputs.version }}