name: Java check with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'oracle'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Get short SHA
      run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
    - name: Generate release note
      run: |
        echo "JTool Release ${{ env.SHORT_SHA }}" >> RELEASE_NOTE
        echo "" >> RELEASE_NOTE
        echo "Update" >> RELEASE_NOTE 
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: JTool-${{ env.SHORT_SHA }}
        path: target/dict-1.0.jar

  release:

    runs-on: macos-latest

    steps:
    - name: Build with Maven
      run: mvn package
    - name: Get short SHA
      run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
    - name: Generate release note
      run: |
        echo "JTool Release ${{ env.SHORT_SHA }}" >> RELEASE_NOTE
        echo "" >> RELEASE_NOTE
        echo "Updated JTool" >> RELEASE_NOTE 
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: JTool-${{ env.SHORT_SHA }}
        path: target/dict-1.0.jar
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        body_path: RELEASE_NOTE
        files: |
          JTool-${{ env.SHORT_SHA }}.jar
          name: JTool release ${{ env.SHORT_SHA }}
          tag_name: ${{ env.SHORT_SHA }}
  